image:
  - Visual Studio 2015
  # - Ubuntu

build: off

test_script:
  - ps:   .\DoTests.ps1
  - pwsh: .\DoTests.ps1 -DontCreateZip

skip_commits:
  files:
    - README.md

artifacts:
  - path: ImportExcel*.zip
    name: ImportExcel
